### ISSUE TITLE
Bug With Menu Bar With Desktop Pointer

### ISSUE THREAD

**Issue by thatbynln** [Denex8Poulose/Encounter#1]
**I recently checked your project and saw a bug with the menu bar.**

i will add some images 
**Details:-**
             browser : Brave, Firefox
             OS         : Arch Linux, Desktop

**ImgS**

![first](https://user-images.githubusercontent.com/107451824/181037148-0edebfdb-2eb5-45a6-9dba-0ad57af42724.png)

![second](https://user-images.githubusercontent.com/107451824/181037230-033fe4d9-bd03-4183-a28d-55f558789f5f.png)

Additional details will be added
Thank You

**Comment by denex-a-poulose** [comment]
Okay ! I will try to fix it .
